name: CI/CD Docker Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t cybersoft-final-project .

    - name: Save image as tarball
      run: docker save cybersoft-final-project > image.tar

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: |
          image.tar
          Dockerfile
        target: ~/deploy/

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/deploy
          docker load < image.tar
          docker stop cybersoft-final || true
          docker rm cybersoft-final || true
          docker run -d --name cybersoft-final -p 1801:5000 cybersoft-final-project
