name: Deploy .NET App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout source
      - name: Checkout source
        uses: actions/checkout@v3

      # Bước 2: Setup .NET 8
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Bước 3: Publish .NET app ra thư mục out/
      - name: Publish .NET project
        run: dotnet publish -c Release -o out

      # Bước 4: Debug - liệt kê file/folder đang có
      - name: List workspace content
        run: |
          echo "Root:"
          ls -al
          echo "out folder:"
          ls -al out

      # Bước 5: Clean source cũ trên VPS
      - name: Clean old source on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            rm -rf /var/www/cybersoft-final-project/*

      # Bước 6: Copy code, Dockerfile, docker-compose.yml lên VPS
      - name: Copy source code to VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: |
            out
            Dockerfile
            docker-compose.yml
          target: /var/www/cybersoft-final-project

      # Bước 7: Restart Docker Compose on VPS
      - name: Restart Docker Compose on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/cybersoft-final-project
            docker compose down
            docker compose up --build -d
